"""empty message

Revision ID: 044b39afadaf
Revises: 98236fabd0a4
Create Date: 2023-04-08 20:01:16.233786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044b39afadaf'
down_revision = '98236fabd0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('passengers',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('cargo_capacity',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('length',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('passengers',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
