"""empty message

Revision ID: 3722e706919f
Revises: 4c90db404490
Create Date: 2023-04-08 16:42:48.581084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3722e706919f'
down_revision = '4c90db404490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=255), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('people_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('history_person')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('history_person', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('birth_year')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
