"""empty message

Revision ID: 523fefb0090c
Revises: 8b5dde5df89c
Create Date: 2023-04-08 17:32:07.039472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523fefb0090c'
down_revision = '8b5dde5df89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_people', sa.Integer(), nullable=True),
    sa.Column('user_id_planets', sa.Integer(), nullable=True),
    sa.Column('user_id_vehicles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_people'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
