"""empty message

Revision ID: 8b5dde5df89c
Revises: 3722e706919f
Create Date: 2023-04-08 17:14:20.225714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5dde5df89c'
down_revision = '3722e706919f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))
        batch_op.drop_column('history')
        batch_op.drop_column('tipes')
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipes', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('history', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('diameter')

    # ### end Alembic commands ###
