"""empty message

Revision ID: d28a6d87228b
Revises: 044b39afadaf
Create Date: 2023-04-08 22:19:42.391152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28a6d87228b'
down_revision = '044b39afadaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id_people',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id_planets',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id_vehicles',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('favorites_user_id_people_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicles', ['user_id_vehicles'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['user_id_planets'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['user_id_people'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_user_id_people_fkey', 'user', ['user_id_people'], ['id'])
        batch_op.alter_column('user_id_vehicles',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id_planets',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id_people',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
