"""empty message

Revision ID: fb3e0884029b
Revises: 523fefb0090c
Create Date: 2023-04-08 17:40:55.445744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3e0884029b'
down_revision = '523fefb0090c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cargo_capacity', sa.Integer(), nullable=False))
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('history')
        batch_op.drop_column('vehicles_id')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicles_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('history', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('length')
        batch_op.drop_column('passengers')

    # ### end Alembic commands ###
